spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://${SUPABASE_POOLER_HOST}:5432/postgres?sslmode=require}
spring.datasource.username=${SUPABASE_DB_USERNAME:postgres.bwwlufqnobdyfhgtdncd}
spring.datasource.password=${SUPABASE_DB_PASSWORD:LAVICTOIRE34_}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=public
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preferQueryMode=simple
